config/routes.rb
GroupConfig::Application.routes.draw do
  get "group_tool/index"

  resources :group_nestings

  resources :groups

  resources :group_categories

  match 'groups/categories/:id' => 'groups#viewByCategory'

  match 'groups/:id/nestgroups' => 'groups#viewNestGroup', :as => :viewNestGroup
  

  root :to => 'group_tool#index', :as=>'group_tool'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_one :group_category
  
  def self.search(search, sort, direction)
    if search
      #where('Group.name LIKE ?', "%#{search}%")
      Group.find_by_sql("select a.*, b.category_name from groups a 
                          join group_categories b on a.category_id = b.id 
                          where a.name like '%#{search}%' or b.category_name like '%#{search}%'
                          order by #{sort} #{direction}")
    else
      scoped
    end
  end
   

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml
  helper_method :sort_column, :sort_direction
  
  def index        
    #@groups = Group.search(params[:search])     
    #@groups = Group.paginate :page=>params[:page], :order=>'id', :per_page=>10
    @groups = Group.search(params[:search], sort_column, sort_direction).paginate(:per_page=> 20, :page=>params[:page], :order=>(sort_column + " " + sort_direction))
    @group_nestings = GroupNesting.all
    
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to(groups_url, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(groups_url, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url,:notice => 'Group was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
  
  # it will show all the groups by a given category id
  def viewByCategory
    @groups = Group.find(:all, :conditions=>["category_id in (?)", params[:id]]).paginate(:per_page=> 20, :page=>params[:page], :order=>(sort_column + " " + sort_direction))
 
  end
  
  #it will show all the nested group under the given group id
  def viewNestGroup
    idstr = []
    @nestingroups = GroupNesting.findNestedGroups(params[:id])
    idstr[0] = params[:id] 
    while @nestingroups.count > 0
      idstr2 = []
      for nid in @nestingroups
        idstr << nid.group_id
        idstr2 << nid.group_id
      end
      @nestingroups = GroupNesting.findNestedGroups(idstr2)
    end
    
    @totalnesting = GroupNesting.findNestedGroups(idstr)
    @groups = Group.search(params[:search], sort_column, sort_direction).paginate(:per_page=> 20, :page=>params[:page], :order=>(sort_column + " " + sort_direction))
    
    respond_to do |format|
      format.html  #viewNestGroup.html.erb
    end
  end
  
  private
  
  def sort_column
    Group.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
   	<!--- <%= f.text_field :category_id %> -->
	<% group_category = GroupCategory.find(:all, :order=>"order_by").map{ |g| [g.category_name, g.id]} %>
	<%= select(:group, :category_id, options_for_select(group_category)) %>	
  </div>
  <div class="field">
    <%= f.label :department_id %><br />
    <%= f.text_field :department_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>


<%= link_to 'Back', group_tool_path %>

app/views/groups/index.html.erb
<table>
	<tr>
		<td>
			<h1>Listing groups</h1>
			<p><font color="red"><%= notice %></font></p>
			
			<%= form_tag groups_path, :method=>'get' do %>
				<%= hidden_field_tag :direction, params[:direction] %>
				<%= hidden_field_tag :sort, params[:sort] %>
				<p>
					<%= text_field_tag :search, params[:search] %>
					<%= submit_tag "Search", :name=>nil %>
				</p>
				
			<% end %>
			
			<table border=1 id="groupTb">
			  <tr>
			    <th><%= sortable "name" %></th>
			    <th><%= sortable "category_id", "Category" %></th>
			    <th><%= sortable "department_id", "Department" %></th>
			    <th></th>
			    <th></th>
			  </tr>
			
			<% @groups.each do |group| %>
			  <tr class="node <%= cycle("even", "odd")%>" onclick="showMsg(<%= group.id%>, this)">
			    <td><%= link_to (group.name), viewNestGroup_path(group) %></td>
			    <td><%= GroupCategory.find_by_id(group.category_id).category_name%></td>
			    <td><%= group.department_id %></td>
			   
			    <td><%= link_to 'Edit', edit_group_path(group) %></td>
			    <td><%= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete %></td>
			  </tr>
			<% end %>
			</table>
			
			<br />
			
			<%= button_to 'Add', new_group_path, :method=>"get" %>
			
			<p><%= will_paginate @groups %></p>
		</td>

		<td valign="top">
			
			<h1>Listing Nested Groups</h1>

			<table border=1>
			  <tr>
			    <th>Name</th>
			    <th>Category</th>
			    <th>Department</th>
			    <th></th>
			    <th></th>
			  </tr>
			<div id="#nestings">
			<% @group_nestings.each do |group_nesting| %>
			  <tr>
			    <td><%= group_nesting.parent_id %></td>
			    <td><%= group_nesting.group_id %></td>

			    <td><%= link_to 'Edit', edit_group_nesting_path(group_nesting) %></td>
			    <td><%= link_to 'Destroy', group_nesting, :confirm => 'Are you sure?', :method => :delete %></td>
			  </tr>
			<% end %>
			</div>
			</table>
			
			<br />
			<%= form_tag new_group_nesting_path, :method=>'get' do%>
				<%= hidden_field_tag :parent_group %>
			<!--<%= button_to 'Add', group_nestings_path, :method=>"get", :disabled=>true, :id=>'addNesting', :onclick=>"exGroup()" %>-->
				<%= submit_tag 'Add',  :disabled=>true, :id=>"addNesting", :onclick=>"storeParentID()", :name=>"addNesting" %>
			<% end %>
		</td>

	</tr>
</table>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', group_tool_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Category:</b>
  <%= @group.category_id %>
</p>

<p>
  <b>Department:</b>
  <%= @group.department_id %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/groups/viewByCategory.html.erb
<h1>View Groups By Category</h1>
<table border=1 >
	<tr>
		<th>Name</th>
		<th>Category</th>
		<th>Department</th>
	</tr>

	<% @groups.each do |group| %>
	  <tr class="node <%= cycle("even", "odd")%>" >
	    <td><%= group.name %></td>
	    <td><%= GroupCategory.find_by_id(group.category_id).category_name%></td>
	    <td><%= group.department_id %></td>
	   
	  </tr>
	<% end %>
</table>

<p><%= will_paginate @groups %></p>

app/views/groups/viewNestGroup.html.erb
<table>
	<tr>
		<td>
			<td>
			<h1>Listing groups</h1>
			<p><font color="red"><%= notice %></font></p>
			
			<%= form_tag groups_path, :method=>'get' do %>
				<%= hidden_field_tag :direction, params[:direction] %>
				<%= hidden_field_tag :sort, params[:sort] %>
				<p>
					<%= text_field_tag :search, params[:search] %>
					<%= submit_tag "Search", :name=>nil %>
				</p>
				
			<% end %>
			
			<table border=1 id="groupTb">
			  <tr>
			    <th><%= sortable "name" %></th>
			    <th><%= sortable "category_id", "Category" %></th>
			    <th><%= sortable "department_id", "Department" %></th>
			    <th></th>
			    <th></th>
			  </tr>
			
			<% @groups.each do |group| %>
			  <tr class="node <%= cycle("even", "odd")%>" onclick="showMsg(<%= group.id%>, this)">
			    <td><%= link_to (group.name), viewNestGroup_path(group) %></td>
			    <td><%= GroupCategory.find_by_id(group.category_id).category_name%></td>
			    <td><%= group.department_id %></td>
			   
			    <td><%= link_to 'Edit', edit_group_path(group) %></td>
			    <td><%= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete %></td>
			  </tr>
			<% end %>
			</table>
			
			<br />
			
			<%= button_to 'Add', new_group_path, :method=>"get" %>
			
			<p><%= will_paginate @groups %></p>
		</td>
		</td>
		<td valign="top">
			<h1>View Nested Groups By Group</h1>
			<table  border=1 >				
				<tr>
					<th>Name</th>
					<th>Category</th>
					<th>Department</th>
				</tr>
			
				<% @totalnesting.each do |nesting| %>
				  <tr class="node <%= cycle("even", "odd")%>" >
				    <!--<td><%= nesting.parent_id %></td>-->
				    <td><%= Group.find(nesting.group_id).name %></td>
				 	<td><%= GroupCategory.find(Group.find(nesting.group_id).category_id).category_name %></td>
					<td><%= Group.find(nesting.group_id).department_id %></td>
				  </tr>
				<% end %>
			</table>
			<%= form_tag new_group_nesting_path, :method=>'get' do%>
				<%= hidden_field_tag :parent_group %>
			<!--<%= button_to 'Add', group_nestings_path, :method=>"get", :disabled=>true, :id=>'addNesting', :onclick=>"exGroup()" %>-->
				<%= submit_tag 'Add',  :disabled=>true, :id=>"addNesting", :onclick=>"storeParentID()", :name=>"addNesting" %>
			<% end %>
		</td>
	</tr>
</table>