config/routes.rb
GroupConfig::Application.routes.draw do
  get "group_tool/index"

  resources :group_nestings

  resources :groups

  resources :group_categories

  match 'groups/categories/:id' => 'groups#viewByCategory'

  match 'groups/:id/nestgroups' => 'groups#viewNestGroup', :as => :viewNestGroup
  

  root :to => 'group_tool#index', :as=>'group_tool'

end

app/models/group_category.rb
class GroupCategory < ActiveRecord::Base
  validates :category_name, :presence=>true
  validates :category_name, :uniqueness=>true
  belongs_to :groups
  belongs_to :group_nesting
end

app/controllers/group_categories_controller.rb
class GroupCategoriesController < ApplicationController
  # GET /group_categories
  # GET /group_categories.xml
  
  helper_method :sort_column, :sort_direction
  def index
    @group_categories = GroupCategory.find(:all, :order=>"order_by")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @group_categories }
    end
  end

  # GET /group_categories/1
  # GET /group_categories/1.xml
  def show
    @group_category = GroupCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group_category }
    end
  end

  # GET /group_categories/new
  # GET /group_categories/new.xml
  def new
    @group_category = GroupCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group_category }
    end
  end

  # GET /group_categories/1/edit
  def edit
    @group_category = GroupCategory.find(params[:id])
  end

  # POST /group_categories
  # POST /group_categories.xml
  def create
    @group_category = GroupCategory.new(params[:group_category])

    respond_to do |format|
      if @group_category.save
        format.html { redirect_to(group_categories_url, :notice => 'Group category was successfully created.') }
        format.xml  { render :xml => @group_category, :status => :created, :location => @group_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /group_categories/1
  # PUT /group_categories/1.xml
  def update
    @group_category = GroupCategory.find(params[:id])

    respond_to do |format|
      if @group_category.update_attributes(params[:group_category])
        format.html { redirect_to(group_categories_url, :notice => 'Group category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /group_categories/1
  # DELETE /group_categories/1.xml
  def destroy
    @group_category = GroupCategory.find(params[:id])
    @group_category.destroy

    respond_to do |format|
      format.html { redirect_to(group_categories_url, :notice => 'Group category was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
  
  
  
end

app/helpers/group_categories_helper.rb
module GroupCategoriesHelper
end

app/views/group_categories/_form.html.erb
<%= form_for(@group_category) do |f| %>
  <% if @group_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_category.errors.count, "error") %> prohibited this group_category from being saved:</h2>

      <ul>
      <% @group_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :category_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_categories/edit.html.erb
<h1>Editing Group Category</h1>

<%= render 'form' %>

<%= link_to 'Back', group_categories_path %>

app/views/group_categories/index.html.erb
<h1>Listing Group Categories</h1>
<p><font color="red"><%= notice %></font></p>
<table border="1" width="30%">
  <tr>
    <th width="70%">Name</th>
    <th></th>
    <th></th>
  </tr>

<% @group_categories.each do |group_category| %>
  <tr class="node <%= cycle("even", "odd")%>">
    <td><%= group_category.category_name %></td>
   
    <td><%= link_to 'Edit', edit_group_category_path(group_category) %></td>
    <td><%= link_to 'Destroy', group_category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'Add', new_group_category_path, :method=>"get" %>

app/views/group_categories/new.html.erb
<h1>New Group Category</h1>

<%= render 'form' %>

<%= link_to 'Back', group_categories_path %>

app/views/group_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group_category.category_name %>
</p>


<%= link_to 'Edit', edit_group_category_path(@group_category) %> |
<%= link_to 'Back', group_categories_path %>

app/views/group_categories/view.html.erb
<h1>View Groups By Category</h1>
<table border=1 >
	<tr>
		<th>Name</th>
		<th>Category</th>
		<th>Department</th>
	</tr>

	<% @groups.each do |group| %>
	  <tr class="node <%= cycle("even", "odd")%>" >
	    <td><%= group.name %></td>
	    <td><%= GroupCategory.find_by_id(group.category_id).category_name%></td>
	    <td><%= group.department_id %></td>
	   
	  </tr>
	<% end %>
</table>

<p><%= will_paginate @groups %></p>